.seg	"text"
start:
	add	%g0, 1, %g1
	sub	%g0, 2, %g2
	or	%g0, 3, %g3
	orn	%g0, 4, %g4
	and	%g0, 5, %g5
	andn	%g0, 6, %g6
	xor	%g0, 7, %g7

	add	%g0, 1, %g1
	sub	%g0, 2, %g2
	or	%g0, 3, %g3
	orn	%g0, 4, %g4
	and	%g0, 5, %g5
	andn	%g0, 6, %g6
	xor	%g0, 7, %g7
	
	add	%g0, 1, %g1
	sub	%g0, 2, %g2
	or	%g0, 3, %g3
	orn	%g0, 4, %g4
	and	%g0, 5, %g5
	andn	%g0, 6, %g6
	xor	%g0, 7, %g7

	
	st	%g1, [%o0]
	

