#define PSR_IMPL_SHIFT 28
#define PSR_IMPL_BITS 4
#define PSR_VER_SHIFT 24
#define PSR_VER_BITS 4
#define PSR_ICC_SHIFT 20
#define PSR_ICC_BITS 4
#define PSR_RESERVED_SHIFT 14
#define PSR_RESERVED_BITS 6
#define PSR_EC_SHIFT 13
#define PSR_EC_BITS 1
#define PSR_EF_SHIFT 12
#define PSR_EF_BITS 1
#define PSR_PIL_SHIFT 8
#define PSR_PIL_BITS 4
#define PSR_S_SHIFT 7
#define PSR_S_BITS 1
#define PSR_PS_SHIFT 6
#define PSR_PS_BITS 1
#define PSR_ET_SHIFT 5
#define PSR_ET_BITS 1
#define PSR_CWP_SHIFT 0
#define PSR_CWP_BITS 5
#define PSR_CWP_ID_MAX 7
#define PSR_IMPL_MASK ((0xffffffff << (32 - PSR_IMPL_SHIFT - PSR_IMPL_BITS)) >> (32 - PSR_IMPL_BITS)) << PSR_IMPL_SHIFT
#define PSR_VER_MASK ((0xffffffff << (32 - PSR_VER_SHIFT - PSR_VER_BITS)) >> (32 - PSR_VER_BITS)) << PSR_VER_SHIFT
#define PSR_ICC_MASK ((0xffffffff << (32 - PSR_ICC_SHIFT - PSR_ICC_BITS)) >> (32 - PSR_ICC_BITS)) << PSR_ICC_SHIFT
#define PSR_RESERVED_MASK ((0xffffffff << (32 - PSR_RESERVED_SHIFT - PSR_RESERVED_BITS)) >> (32 - PSR_RESERVED_BITS)) << PSR_RESERVED_SHIFT
#define PSR_EC_MASK ((0xffffffff << (32 - PSR_EC_SHIFT - PSR_EC_BITS)) >> (32 - PSR_EC_BITS)) << PSR_EC_SHIFT
#define PSR_EF_MASK ((0xffffffff << (32 - PSR_EF_SHIFT - PSR_EF_BITS)) >> (32 - PSR_EF_BITS)) << PSR_EF_SHIFT
#define PSR_PIL_MASK ((0xffffffff << (32 - PSR_PIL_SHIFT - PSR_PIL_BITS)) >> (32 - PSR_PIL_BITS)) << PSR_PIL_SHIFT
#define PSR_S_MASK ((0xffffffff << (32 - PSR_S_SHIFT - PSR_S_BITS)) >> (32 - PSR_S_BITS)) << PSR_S_SHIFT
#define PSR_PS_MASK ((0xffffffff << (32 - PSR_PS_SHIFT - PSR_PS_BITS)) >> (32 - PSR_PS_BITS)) << PSR_PS_SHIFT
#define PSR_ET_MASK ((0xffffffff << (32 - PSR_ET_SHIFT - PSR_ET_BITS)) >> (32 - PSR_ET_BITS)) << PSR_ET_SHIFT
#define PSR_CWP_MASK ((0xffffffff << (32 - PSR_CWP_SHIFT - PSR_CWP_BITS)) >> (32 - PSR_CWP_BITS)) << PSR_CWP_SHIFT

#define TBR_TT_MASK 4080
#define TBR_ADDRESS_OFFSET 12

#define VIRT_CPU_PSR_OFFSET	0
#define VIRT_CPU_WIM_OFFSET	(VIRT_CPU_PSR_OFFSET + 4)
#define VIRT_CPU_TBR_OFFSET	(VIRT_CPU_WIM_OFFSET + 4)
#define VIRT_CPU_BACKUP_G0_OFFSET	(VIRT_CPU_TBR_OFFSET + 4)
#define VIRT_CPU_BACKUP_G1_OFFSET	(VIRT_CPU_BACKUP_G0_OFFSET + 4)
#define VIRT_CPU_BACKUP_G2_OFFSET	(VIRT_CPU_BACKUP_G1_OFFSET + 4)
#define VIRT_CPU_BACKUP_G3_OFFSET	(VIRT_CPU_BACKUP_G2_OFFSET + 4)
#define VIRT_CPU_BACKUP_G4_OFFSET	(VIRT_CPU_BACKUP_G3_OFFSET + 4)
#define VIRT_CPU_BACKUP_G5_OFFSET	(VIRT_CPU_BACKUP_G4_OFFSET + 4)
#define VIRT_CPU_BACKUP_G6_OFFSET	(VIRT_CPU_BACKUP_G5_OFFSET + 4)
#define VIRT_CPU_BACKUP_G7_OFFSET	(VIRT_CPU_BACKUP_G6_OFFSET + 4)
#define VIRT_CPU_BACKUP_O0_OFFSET	(VIRT_CPU_BACKUP_G7_OFFSET + 4)
#define VIRT_CPU_BACKUP_O1_OFFSET	(VIRT_CPU_BACKUP_O0_OFFSET + 4)
#define VIRT_CPU_BACKUP_O2_OFFSET	(VIRT_CPU_BACKUP_O1_OFFSET + 4)
#define VIRT_CPU_BACKUP_O3_OFFSET	(VIRT_CPU_BACKUP_O2_OFFSET + 4)
#define VIRT_CPU_BACKUP_O4_OFFSET	(VIRT_CPU_BACKUP_O3_OFFSET + 4)
#define VIRT_CPU_BACKUP_O5_OFFSET	(VIRT_CPU_BACKUP_O4_OFFSET + 4)
#define VIRT_CPU_BACKUP_O6_OFFSET	(VIRT_CPU_BACKUP_O5_OFFSET + 4)
#define VIRT_CPU_BACKUP_O7_OFFSET	(VIRT_CPU_BACKUP_O6_OFFSET + 4)
#define VIRT_CPU_BACKUP_L0_OFFSET	(VIRT_CPU_BACKUP_O7_OFFSET + 4)
#define VIRT_CPU_BACKUP_L1_OFFSET	(VIRT_CPU_BACKUP_L0_OFFSET + 4)
#define VIRT_CPU_BACKUP_L2_OFFSET	(VIRT_CPU_BACKUP_L1_OFFSET + 4)
#define VIRT_CPU_BACKUP_L3_OFFSET	(VIRT_CPU_BACKUP_L2_OFFSET + 4)
#define VIRT_CPU_BACKUP_L4_OFFSET	(VIRT_CPU_BACKUP_L3_OFFSET + 4)
#define VIRT_CPU_BACKUP_L5_OFFSET	(VIRT_CPU_BACKUP_L4_OFFSET + 4)
#define VIRT_CPU_BACKUP_L6_OFFSET	(VIRT_CPU_BACKUP_L5_OFFSET + 4)
#define VIRT_CPU_BACKUP_L7_OFFSET	(VIRT_CPU_BACKUP_L6_OFFSET + 4)
#define VIRT_CPU_BACKUP_I0_OFFSET	(VIRT_CPU_BACKUP_L7_OFFSET + 4)
#define VIRT_CPU_BACKUP_I1_OFFSET	(VIRT_CPU_BACKUP_I0_OFFSET + 4)
#define VIRT_CPU_BACKUP_I2_OFFSET	(VIRT_CPU_BACKUP_I1_OFFSET + 4)
#define VIRT_CPU_BACKUP_I3_OFFSET	(VIRT_CPU_BACKUP_I2_OFFSET + 4)
#define VIRT_CPU_BACKUP_I4_OFFSET	(VIRT_CPU_BACKUP_I3_OFFSET + 4)
#define VIRT_CPU_BACKUP_I5_OFFSET	(VIRT_CPU_BACKUP_I4_OFFSET + 4)
#define VIRT_CPU_BACKUP_I6_OFFSET	(VIRT_CPU_BACKUP_I5_OFFSET + 4)
#define VIRT_CPU_BACKUP_I7_OFFSET	(VIRT_CPU_BACKUP_I6_OFFSET + 4)
#define VIRT_CPU_BACKUP_PSR_OFFSET	(VIRT_CPU_BACKUP_I7_OFFSET + 4)

#define FMT3_OP_SHIFT 30
#define FMT3_OP_BITS 2
#define FMT3_RD_SHIFT 25
#define FMT3_RD_BITS 5
#define FMT3_OP3_SHIFT 19
#define FMT3_OP3_BITS 6
#define FMT3_RS1_SHIFT 14
#define FMT3_RS1_BITS 5
#define FMT3_I_SHIFT 13
#define FMT3_I_BITS 1
#define FMT3_ASI_SHIFT 5
#define FMT3_ASI_BITS 8
#define FMT3_RS2_SHIFT 0
#define FMT3_RS2_BITS 5
#define FMT3_OPF_SHIFT 5
#define FMT3_OPF_BITS 9
#define FMT3_SIMM13_SHIFT 0
#define FMT3_SIMM13_BITS 13
#define FMT3_OP_MASK ((0xffffffff << (32 - FMT3_OP_SHIFT - FMT3_OP_BITS)) >> (32 - FMT3_OP_BITS)) << FMT3_OP_SHIFT
#define FMT3_RD_MASK ((0xffffffff << (32 - FMT3_RD_SHIFT - FMT3_RD_BITS)) >> (32 - FMT3_RD_BITS)) << FMT3_RD_SHIFT
#define FMT3_OP3_MASK ((0xffffffff << (32 - FMT3_OP3_SHIFT - FMT3_OP3_BITS)) >> (32 - FMT3_OP3_BITS)) << FMT3_OP3_SHIFT
#define FMT3_RS1_MASK ((0xffffffff << (32 - FMT3_RS1_SHIFT - FMT3_RS1_BITS)) >> (32 - FMT3_RS1_BITS)) << FMT3_RS1_SHIFT
#define FMT3_I_MASK ((0xffffffff << (32 - FMT3_I_SHIFT - FMT3_I_BITS)) >> (32 - FMT3_I_BITS)) << FMT3_I_SHIFT
#define FMT3_ASI_MASK ((0xffffffff << (32 - FMT3_ASI_SHIFT - FMT3_ASI_BITS)) >> (32 - FMT3_ASI_BITS)) << FMT3_ASI_SHIFT
#define FMT3_RS2_MASK ((0xffffffff << (32 - FMT3_RS2_SHIFT - FMT3_RS2_BITS)) >> (32 - FMT3_RS2_BITS)) << FMT3_RS2_SHIFT
#define FMT3_OPF_MASK ((0xffffffff << (32 - FMT3_OPF_SHIFT - FMT3_OPF_BITS)) >> (32 - FMT3_OPF_BITS)) << FMT3_OPF_SHIFT
#define FMT3_SIMM13_MASK ((0xffffffff << (32 - FMT3_SIMM13_SHIFT - FMT3_SIMM13_BITS)) >> (32 - FMT3_SIMM13_BITS)) << FMT3_SIMM13_SHIFT

